games/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
 
  resources :games
 
  root 'welcome#index'
end

games/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

games/app/models/game.rb
class Game < ApplicationRecord
end

games/app/models/moba.rb
class Moba < ApplicationRecord
end

games/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

games/app/controllers/games_controller.rb
class GamesController < ApplicationController
def index
	@game = Game.all
end

def show			
	@game = Game.find(params[:id])
end

def new
end

def edit
  @game = Game.find(params[:id])
end
		
def create
  @game = Game.new(game_params)
 
  @game.save
  redirect_to @game
end

def update
  @game = Game.find(params[:id])
 
  if @game.update(game_params)
    redirect_to @game
  else
    render 'edit'
  end
end

def destroy
  @game = Game.find(params[:id])
  @game.destroy
 
  redirect_to games_path
end
 
private
  def game_params
    params.require(:game).permit(:title, :text)
  end
end

games/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

games/app/helpers/application_helper.rb
module ApplicationHelper
end

games/app/helpers/games_helper.rb
module GamesHelper
end

games/app/helpers/welcome_helper.rb
module WelcomeHelper
end

games/app/views/games/edit.erb
<h1>Editing game</h1>
 
<%= form_with(model: @game, local: true) do |form| %>
 
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', games_path %>

games/app/views/games/index.erb
<h1>Listing games</h1>
 <%= link_to 'New game', new_game_path %>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="2"></th>
  </tr>
 
  <% @game.each do |game| %>
    <tr>
      <td><%= game.title %></td>
      <td><%= game.text %></td>
      <td><%= link_to 'Show', game_path(game) %></td>
      <td><%= link_to 'Edit', edit_game_path(game) %></td>
      <td><%= link_to 'Destroy', game_path(game),
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
      </td>
    </tr>
  <% end %>
</table>

games/app/views/games/new.erb
<h1>New game</h1>
<%= form_with scope: :game, url: games_path, local: true do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>
<%= link_to 'Back', games_path %>

games/app/views/games/show.erb
<p>
  <strong>Title:</strong>
  <%= @game.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @game.text %>
</p>
<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

games/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Games</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>