tanks/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
 
  resources :tanks
 
  root 'welcome#index'
end

tanks/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

tanks/app/models/tank.rb
class Tank < ApplicationRecord
end

tanks/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

tanks/app/controllers/tanks_controller.rb
class TanksController < ApplicationController
	def index
	@tank = Tank.all
end

def show			
	@tank = Tank.find(params[:id])
end

def new
end

def edit
  @tank = Tank.find(params[:id])
end
		
def create
  @tank = Tank.new(tank_params)
 
  @tank.save
  redirect_to @tank
end

def update
  @tank = Tank.find(params[:id])
 
  if @tank.update(tank_params)
    redirect_to @tank
  else
    render 'edit'
  end
end

def destroy
  @tank = Tank.find(params[:id])
  @tank.destroy
 
  redirect_to tanks_path
end
 
private
  def tank_params
    params.require(:tank).permit(:title, :text)
  end
end

tanks/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

tanks/app/helpers/application_helper.rb
module ApplicationHelper
end

tanks/app/helpers/tanks_helper.rb
module TanksHelper
end

tanks/app/helpers/welcome_helper.rb
module WelcomeHelper
end

tanks/app/views/tanks/edit.erb
<h1>Editing tank</h1>
 
<%= form_with(model: @tank, local: true) do |form| %>
 
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', tanks_path %>

tanks/app/views/tanks/index.erb
<h1>Listing tanks</h1>
 <%= link_to 'New tank', new_tank_path %>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="2"></th>
  </tr>
 
  <% @tank.each do |tank| %>
    <tr>
      <td><%= tank.title %></td>
      <td><%= tank.text %></td>
      <td><%= link_to 'Show', tank_path(tank) %></td>
      <td><%= link_to 'Edit', edit_tank_path(tank) %></td>
      <td><%= link_to 'Destroy', tank_path(tank),
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
      </td>
    </tr>
  <% end %>
</table>

tanks/app/views/tanks/new.erb
<h1>New tank</h1>
<%= form_with scope: :tank, url: tanks_path, local: true do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>
<%= link_to 'Back', tanks_path %>

tanks/app/views/tanks/show.erb
<p>
  <strong>Title:</strong>
  <%= @tank.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @tank.text %>
</p>
<%= link_to 'Edit', edit_tank_path(@tank) %> |
<%= link_to 'Back', tanks_path %>

tanks/app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to 'Tanks', controller: 'tanks' %>