planes/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
 
  resources :planes
 
  root 'welcome#index'
end

planes/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

planes/app/models/plane.rb
class Plane < ApplicationRecord
end

planes/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

planes/app/controllers/planes_controller.rb
class PlanesController < ApplicationController
def index
	@plane = Plane.all
end

def show			
	@plane = Plane.find(params[:id])
end

def new
end

def edit
  @plane = Plane.find(params[:id])
end
		
def create
  @plane = Plane.new(plane_params)
 
  @plane.save
  redirect_to @plane
end

def update
  @plane = Plane.find(params[:id])
 
  if @plane.update(plane_params)
    redirect_to @plane
  else
    render 'edit'
  end
end

def destroy
  @plane = Plane.find(params[:id])
  @plane.destroy
 
  redirect_to planes_path
end
 
private
  def plane_params
    params.require(:plane).permit(:title, :text)
  end
end

planes/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

planes/app/helpers/application_helper.rb
module ApplicationHelper
end

planes/app/helpers/planes_helper.rb
module PlanesHelper
end

planes/app/helpers/welcome_helper.rb
module WelcomeHelper
end

planes/app/views/planes/edit.erb
<h1>Editing plane</h1>
 
<%= form_with(model: @plane, local: true) do |form| %>
 
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', planes_path %>

planes/app/views/planes/index.erb
<h1>Listing planes</h1>
 <%= link_to 'New plane', new_plane_path %>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="2"></th>
  </tr>
 
  <% @plane.each do |plane| %>
    <tr>
      <td><%= plane.title %></td>
      <td><%= plane.text %></td>
      <td><%= link_to 'Show', plane_path(plane) %></td>
      <td><%= link_to 'Edit', edit_plane_path(plane) %></td>
      <td><%= link_to 'Destroy', plane_path(plane),
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
      </td>
    </tr>
  <% end %>
</table>

planes/app/views/planes/new.erb
<h1>New plane</h1>
<%= form_with scope: :plane, url: planes_path, local: true do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>
<%= link_to 'Back', planes_path %>

planes/app/views/planes/show.erb
<p>
  <strong>Title:</strong>
  <%= @plane.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @plane.text %>
</p>
<%= link_to 'Edit', edit_plane_path(@plane) %> |
<%= link_to 'Back', planes_path %>