bands/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
 
  resources :bands
 
  root 'welcome#index'
end

bands/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

bands/app/models/band.rb
class Band < ApplicationRecord
end

bands/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

bands/app/controllers/bands_controller.rb
class BandsController < ApplicationController
def index
	@band = Band.all
end

def show			
	@band = Band.find(params[:id])
end

def new
end

def edit
  @band = Band.find(params[:id])
end
		
def create
  @band = Band.new(band_params)
 
  @band.save
  redirect_to @band
end

def update
  @band = Band.find(params[:id])
 
  if @band.update(band_params)
    redirect_to @band
  else
    render 'edit'
  end
end

def destroy
  @band = Band.find(params[:id])
  @band.destroy
 
  redirect_to bands_path
end
 
private
  def band_params
    params.require(:band).permit(:title, :text)
  end
end

bands/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

bands/app/helpers/application_helper.rb
module ApplicationHelper
end

bands/app/helpers/bands_helper.rb
module BandsHelper
end

bands/app/helpers/welcome_helper.rb
module WelcomeHelper
end

bands/app/views/bands/edit.erb
<h1>Editing band</h1>
 
<%= form_with(model: @band, local: true) do |form| %>
 
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', bands_path %>

bands/app/views/bands/index.erb
<h1>Listing bands</h1>
 <%= link_to 'New band', new_band_path %>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="2"></th>
  </tr>
 
  <% @band.each do |band| %>
    <tr>
      <td><%= band.title %></td>
      <td><%= band.text %></td>
      <td><%= link_to 'Show', band_path(band) %></td>
      <td><%= link_to 'Edit', edit_band_path(band) %></td>
      <td><%= link_to 'Destroy', band_path(band),
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
      </td>
    </tr>
  <% end %>
</table>

bands/app/views/bands/new.erb
<h1>New band</h1>
<%= form_with scope: :band, url: bands_path, local: true do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>
<%= link_to 'Back', bands_path %>

bands/app/views/bands/show.erb
<p>
  <strong>Title:</strong>
  <%= @band.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @band.text %>
</p>
<%= link_to 'Edit', edit_band_path(@band) %> |
<%= link_to 'Back', bands_path %>